//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.03 at 02:10:08 AM UZT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uws.provider.com/")
package com.provider.uws;
